
package presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static presentacion.MenuMostrarTodos.modelo;


public class MenuEliminar extends javax.swing.JFrame {
    //static MenuMostrarTodos todos= new MenuMostrarTodos();
    static MenuPrincipal menuPrincipal= new MenuPrincipal();
    static DefaultTableModel modelo= new DefaultTableModel(){
    
        public boolean isCellEditable(int row, int column){
        return false;
        } 
    };
    
    public MenuEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.addColumn(" NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("TEL. FIJO");
        modelo.addColumn("TEL. MÓVIL");
        modelo.addColumn("CORREO ");
        modelo.addColumn("DIRECCIÓN");
        Tabla.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BotonRegresoMenu = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 640, 230));

        BotonRegresoMenu.setBackground(new java.awt.Color(0, 153, 205));
        BotonRegresoMenu.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        BotonRegresoMenu.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegresoMenu.setText("Regresar al Menú Principal");
        BotonRegresoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegresoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        BotonEliminar.setBackground(new java.awt.Color(0, 153, 255));
        BotonEliminar.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresoMenuActionPerformed
        
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresoMenuActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        
        int FilaSelec = Tabla.getSelectedRow();
        if(FilaSelec>=0)
        {
            
            modelo.removeRow(FilaSelec);
            menuPrincipal.menuTodos.modelo.removeRow(FilaSelec);
            menuPrincipal.menuVerUno.modelo.removeRow(FilaSelec);
            menuPrincipal.agenda.libreta.remove(FilaSelec);
            menuPrincipal.menuModificar.modelo.removeRow(FilaSelec);
            JOptionPane.showMessageDialog(this, "Contacto eliminado correctamente");
            menuPrincipal.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un contacto");
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonRegresoMenu;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
